### ISSUE TITLE
Problem with Keycloak SP Metadata

### ISSUE THREAD

**Issue by FabrizioGreco** [italia/spid-keycloak-provider#68]
Hi,

I use Keycloak and I need to integrate it with SPID for login.
I've configured https://github.com/italia/spid-saml-check to test SPID login locally, but when I try to download the Metadata SP from the URL, I get this error:
![image](https://github.com/italia/spid-keycloak-provider/assets/53128434/6bc13e8c-1baf-46a7-9cbc-8c7c386f9318)

I have tried to download the metadata from these pages:

![image](https://github.com/italia/spid-keycloak-provider/assets/53128434/779f56b6-6ae0-4d33-9ee4-9bd1f83736a3)
![image](https://github.com/italia/spid-keycloak-provider/assets/53128434/965cce14-6d62-458a-bd3c-ed74f83c9c89)

but the error persists.

I have searched online but found nothing. Where can I find the correct Keycloak metadata SP to download?

**Comment by nicolabeghin** [comment]
The SPID metadata URL is like `https://<keycloak>/realms/realmname/spid-sp-metadata` as per [Wiki](https://github.com/italia/spid-keycloak-provider/wiki/Generating-SP-metadata#automatic-sp-metadata-generation)
<img width="1437" alt="image" src="https://github.com/italia/spid-keycloak-provider/assets/2743637/a19c4e6d-ae6a-4638-a198-32cb7616f04d">

Being a custom endpoint it's shown only after the IdP has been set up, in the custom field `Metadata URL` (there's no other way at the moment due to how Keycloak handles custom metadata URLs)

<img width="1437" alt="image" src="https://github.com/italia/spid-keycloak-provider/assets/2743637/f65490fc-adc3-4653-bcc2-7e8b96911861">
